In [4]:
import numpy as np

# Definindo os coeficientes do sistema de equações
coeficientes = np.array([[1, 0, 1],
                         [1, 1, 1],
                         [0, 1, 0]])

# Definindo os resultados das equações
resultados = np.array([1, 3, 2])

# Verificando se a matriz dos coeficientes é singular
if np.linalg.matrix_rank(coeficientes) != np.linalg.matrix_rank(np.column_stack((coeficientes, resultados))):
    print("A matriz dos coeficientes é singular. O sistema não tem solução única.")
else:
    # Resolvendo o sistema de equações
    solucao = np.linalg.solve(coeficientes, resultados)

    print("Solução:")
    print("x =", solucao[0])
    print("y =", solucao[1])
    print("z =", solucao[2])

LinAlgError: Singular matrix

In [12]:
import numpy as np

# Definindo os coeficientes do sistema de equações como float64
coeficientes = np.array([[1.0, 0.0, 1.0],
                         [1.0, 1.0, 1.0],
                         [0.0, 1.0, 0.0]])

# Definindo os resultados das equações como float64
resultados = np.array([1.0, 3.0, 2.0])

# Verificando se a matriz dos coeficientes é singular
if np.linalg.matrix_rank(coeficientes) != np.linalg.matrix_rank(np.column_stack((coeficientes, resultados))):
    print("A matriz dos coeficientes é singular. O sistema não tem solução única.")
else:
    # Implementando a eliminação gaussiana
    n = len(resultados)
    x = np.zeros(n)

    for i in range(n):
        # Aplicando o pivotamento parcial
        max_index = np.argmax(np.abs(coeficientes[i:, i])) + i
        coeficientes[[i, max_index]] = coeficientes[[max_index, i]]
        resultados[[i, max_index]] = resultados[[max_index, i]]

        # Eliminação gaussiana
        for j in range(i+1, n):
            factor = coeficientes[j, i] / coeficientes[i, i]
            resultados[j] -= factor * resultados[i]
            coeficientes[j, i:] -= factor * coeficientes[i, i:]
            
            print(coeficientes)

    # Resolvendo o sistema triangular superior
    for i in range(n-1, -1, -1):
        x[i] = (resultados[i] - np.dot(coeficientes[i, i+1:], x[i+1:])) / coeficientes[i, i]
    

    print("Solução:")
    print("x =", x[0])
    print("y =", x[1])
    print("z =", x[2])


[[1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Solução:
x = nan
y = nan
z = nan


C:\Users\Diogo\AppData\Local\Temp\ipykernel_5068\3833277138.py:35: RuntimeWarning: invalid value encountered in scalar divide
  x[i] = (resultados[i] - np.dot(coeficientes[i, i+1:], x[i+1:])) / coeficientes[i, i]
