In [24]:
import numpy as np

def transicao_inicial():
    # Definir a matriz de transição inicial
    P = np.array([[0.7, 0.2, 0.2],
                  [0.2, 0.6, 0.3],
                  [0.1, 0.2, 0.5]])
    return P

def calcular_market_share(P, distribuicao_inicial, meses):
    # Inicializar a distribuição de mercado com a distribuição inicial
    market_share = distribuicao_inicial.copy()

    # Calcular a matriz de transição elevada a n
    P_n = np.linalg.matrix_power(P, meses)
    print('matriz de transiçao inicial')
    print(P)
    print('numero de meses')
    print(meses)
    print('matriz de transiçao apos os meses')
    print(P_n)
    # Calcular o market share após n meses
    market_share_final = np.dot(market_share, P_n)

    return market_share_final


# Calcular a matriz de transição inicial
P = transicao_inicial()

# Distribuição inicial de mercado
distribuicao_inicial = np.array([0.5, 0.2, 0.3])

# Número de meses
meses = int(input("Digite o número de meses para calcular o market share: "))

# Calcular o market share após n meses
market_share_final = calcular_market_share(P, distribuicao_inicial, meses)

# Exibir o market share inicial
print(f"Market Share inicial")
for i, marca in enumerate(['O', 'M', 'Q']):
    print(f"{marca}: {distribuicao_inicial[i]*100:.2f}%")
# Exibir o market share final
print(f"Market Share após {meses} meses:")
for i, marca in enumerate(['O', 'M', 'Q']):
    print(f"{marca}: {market_share_final[i]*100:.2f}%")




matriz de transiçao inicial
[[0.7 0.2 0.2]
 [0.2 0.6 0.3]
 [0.1 0.2 0.5]]
numero de meses
12
matriz de transiçao apos os meses
[[0.40014648 0.39990234 0.39990234]
 [0.37135529 0.37147763 0.3714771 ]
 [0.22849822 0.22862003 0.22862056]]
Market Share inicial
O: 50.00%
M: 20.00%
Q: 30.00%
Market Share após 12 meses:
O: 34.29%
M: 34.28%
Q: 34.28%
