In [1]:
import numpy as np

# Definindo a matriz dada
matriz = np.array([[0.0, 3.0, 7.0, 3.0, 8.0, 2.0],
                   [1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
                   [0.0, 0.0, 1.0, 1.0, 0.0, 0.0],
                   [0.0, 0.0, 0.0, 0.0, 1.0, 1.0]])

def reduzir_matriz(matriz):
    num_linhas, num_colunas = matriz.shape
    for coluna_pivo in range(num_colunas):
        # Verifica se há elementos na sequência antes de calcular o índice da linha do pivô
        if coluna_pivo < num_linhas:
            # Encontra o índice da linha com o maior elemento em valor absoluto na coluna do pivô
            linha_pivo = np.argmax(matriz[coluna_pivo:, coluna_pivo]) + coluna_pivo

            # Troca as linhas se necessário para colocar o pivô na linha corrente
            if linha_pivo != coluna_pivo:
                matriz[[linha_pivo, coluna_pivo]] = matriz[[coluna_pivo, linha_pivo]]

            # Divide a linha do pivô pelo valor do pivô para torná-lo 1
            pivot = matriz[coluna_pivo, coluna_pivo]
            if pivot != 0:
                matriz[coluna_pivo] = matriz[coluna_pivo] / pivot

            # Subtrai múltiplos da linha do pivô das linhas abaixo para fazer os elementos abaixo do pivô iguais a zero
            for linha in range(coluna_pivo + 1, num_linhas):
                coeficiente = matriz[linha, coluna_pivo]
                matriz[linha] -= coeficiente * matriz[coluna_pivo]
            print("pivot")
            print(pivot)
            print('resultado pivotado')
            print(matriz)

    return matriz

# Escalonamento da matriz
matriz_reduzida_manual = reduzir_matriz(matriz.copy())



pivot
1.0
resultado pivotado
[[1. 1. 0. 0. 0. 0.]
 [0. 3. 7. 3. 8. 2.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1.]]
pivot
3.0
resultado pivotado
[[1.         1.         0.         0.         0.         0.        ]
 [0.         1.         2.33333333 1.         2.66666667 0.66666667]
 [0.         0.         1.         1.         0.         0.        ]
 [0.         0.         0.         0.         1.         1.        ]]
pivot
1.0
resultado pivotado
[[1.         1.         0.         0.         0.         0.        ]
 [0.         1.         2.33333333 1.         2.66666667 0.66666667]
 [0.         0.         1.         1.         0.         0.        ]
 [0.         0.         0.         0.         1.         1.        ]]
pivot
0.0
resultado pivotado
[[1.         1.         0.         0.         0.         0.        ]
 [0.         1.         2.33333333 1.         2.66666667 0.66666667]
 [0.         0.         1.         1.         0.         0.        ]
 [0.         0.         0.         0. 

In [3]:
import numpy as np

# Definindo os coeficientes do sistema de equações
coeficientes = np.array([[1, 0, 1],
                         [1, 1, 1],
                         [0, 1, 0]])

# Calculando o posto da matriz
posto = np.linalg.matrix_rank(coeficientes)

# Calculando a determinante da matriz
determinante = np.linalg.det(coeficientes)

print("Posto da matriz dos coeficientes:", posto)
print("Determinante da matriz dos coeficientes:", determinante)

# Verificando as possibilidades com base no posto e na determinante
if determinante != 0:
    if posto == coeficientes.shape[0]:
        print("O sistema tem uma única solução.")
    else:
        print("O sistema tem infinitas soluções.")
else:
    print("O sistema é inconsistente ou possui um número infinito de soluções.")


Posto da matriz dos coeficientes: 2
Determinante da matriz dos coeficientes: 0.0
O sistema é inconsistente ou possui um número infinito de soluções.


In [6]:
import numpy as np

# Definindo a matriz dos coeficientes do sistema homogêneo
matriz_coeficientes_homogeneo = np.array([[0, 3, 7, 3, 8, 2],
                                          [1, 1, 0, 0, 0, 0],
                                          [0, 0, 1, 1, 0, 0],
                                          [0, 0, 0, 0, 1, 1]])

# Verificando se a matriz tem uma solução não trivial
solucao_trivial = np.all(np.linalg.solve(matriz_coeficientes_homogeneo, np.zeros(matriz_coeficientes_homogeneo.shape[0])) == 0)

if solucao_trivial:
    print("A matriz dos coeficientes representa um sistema homogêneo.")
    print("O sistema homogêneo tem apenas a solução trivial, onde todas as incógnitas são zero.")
else:
    print("A matriz dos coeficientes representa um sistema homogêneo, mas tem uma solução não trivial.")


LinAlgError: Last 2 dimensions of the array must be square