In [10]:
import numpy as np

def matriz_inversa(matriz):
    n = len(matriz)
    
    # Criar uma matriz aumentada [matriz | Identidade]
    matriz_aumentada = np.hstack([matriz, np.eye(n)])
    print('matriz aumentada')
    print(matriz_aumentada)
    # Aplicar operações elementares para transformar a parte esquerda em uma matriz identidade
    for i in range(n):
        # Dividir a linha i pelo elemento diagonal para tornar o elemento diagonal 1
        elemento_diagonal = matriz_aumentada[i][i]
        matriz_aumentada[i] /= elemento_diagonal
        
        # Zerar todos os elementos abaixo do elemento diagonal
        for j in range(i + 1, n):
            fator_diagonal = matriz_aumentada[j][i]
            matriz_aumentada[j] -= fator_diagonal * matriz_aumentada[i]
            print('fator diagonal')
            print(fator_diagonal)
            print('matriz aumentada')
            print(matriz_aumentada)
        
    
    # Zerar todos os elementos acima do elemento diagonal
    for i in range(n - 1, -1, -1):
        for j in range(i - 1, -1, -1):
            fator_diagonal = matriz_aumentada[j][i]
            matriz_aumentada[j] -= fator_diagonal * matriz_aumentada[i]
            print('fator diagonal')
            print(fator_diagonal)
            print('matriz aumentada')
            print(matriz_aumentada)
        
    

    # Extrair a parte direita (a inversa) da matriz aumentada
    inversa = matriz_aumentada[:, n:]
    
    return inversa

# Teste com a matriz fornecida no exemplo
matriz = np.array([[2, 1], [4, 3]])
inversa = matriz_inversa(matriz)
print("Matriz inversa:")
print(inversa)


matriz aumentada
[[2. 1. 1. 0.]
 [4. 3. 0. 1.]]
fator diagonal
4.0
matriz aumentada
[[ 1.   0.5  0.5  0. ]
 [ 0.   1.  -2.   1. ]]
fator diagonal
0.5
matriz aumentada
[[ 1.   0.   1.5 -0.5]
 [ 0.   1.  -2.   1. ]]
Matriz inversa:
[[ 1.5 -0.5]
 [-2.   1. ]]
