Suponha que um banco oferece cinco tipos de investimentos para seus clientes: conservador (C), moderado (M), arrojado (A), agressivo (AG) e ultra-agressivo (UA). A cada mês, um cliente pode manter seu investimento atual ou trocar para outro tipo de investimento, de acordo com as seguintes probabilidades de transição:

Um cliente conservador tem 80% de chance de permanecer conservador, 10% de chance de mudar para um investimento moderado, 5% de chance de mudar para um investimento arrojado, 3% de chance de mudar para um investimento agressivo e 2% de chance de mudar para um investimento ultra-agressivo.
Um cliente moderado tem 70% de chance de permanecer moderado, 15% de chance de mudar para um investimento conservador, 10% de chance de mudar para um investimento arrojado, 3% de chance de mudar para um investimento agressivo e 2% de chance de mudar para um investimento ultra-agressivo.
Um cliente arrojado tem 60% de chance de permanecer arrojado, 15% de chance de mudar para um investimento conservador, 10% de chance de mudar para um investimento moderado, 10% de chance de mudar para um investimento agressivo e 5% de chance de mudar para um investimento ultra-agressivo.
Um cliente agressivo tem 50% de chance de permanecer agressivo, 20% de chance de mudar para um investimento conservador, 10% de chance de mudar para um investimento moderado, 10% de chance de mudar para um investimento arrojado e 10% de chance de mudar para um investimento ultra-agressivo.
Um cliente ultra-agressivo tem 40% de chance de permanecer ultra-agressivo, 20% de chance de mudar para um investimento conservador, 15% de chance de mudar para um investimento moderado, 15% de chance de mudar para um investimento arrojado e 10% de chance de mudar para um investimento agressivo.
O problema consiste em determinar a distribuição dos clientes entre os cinco tipos de investimento após um certo número de meses e calcular o market share de cada tipo de investimento.

Agora vamos desenvolver a solução matemática e implementar em Python.


In [5]:
import numpy as np

def transicao_inicial():
    # Definir a matriz de transição inicial
    P = np.array([[0.8, 0.1, 0.05, 0.03, 0.02],
                  [0.15, 0.7, 0.1, 0.03, 0.02],
                  [0.15, 0.1, 0.6, 0.1, 0.05],
                  [0.2, 0.1, 0.1, 0.5, 0.1],
                  [0.2, 0.15, 0.15, 0.1, 0.4]])
    return P

def calcular_market_share(P, distribuicao_inicial, meses):
    # Inicializar a distribuição de mercado com a distribuição inicial
    market_share = distribuicao_inicial.copy()

    # Calcular a matriz de transição elevada a n
    P_n = np.linalg.matrix_power(P, meses)
    print('matriz de transiçao inicial')
    print(P)
    print('numero de meses')
    print(meses)
    print('matriz de transiçao apos os meses')
    print(P_n)
    # Calcular o market share após n meses
    market_share_final = np.dot(market_share, P_n)

    return market_share_final


# Calcular a matriz de transição inicial
P = transicao_inicial()

# Distribuição inicial de mercado
distribuicao_inicial = np.array([0.2, 0.2, 0.2, 0.2, 0.2])

# Número de meses
meses = int(input("Digite o número de meses para calcular o market share: "))

# Calcular o market share após n meses
market_share_final = calcular_market_share(P, distribuicao_inicial, meses)

tipos_investimento = ['Conservador', 'Moderado', 'Arrojado', 'Agressivo', 'Ultra-agressivo']
# Exibir o market share inicial
print("Market Share inicial")
for i, tipo in enumerate(tipos_investimento):
        print(f"{tipo}: {distribuicao_inicial[i]*100:.2f}%")
print(f"Market Share após {meses} meses:")


for i, tipo in enumerate(tipos_investimento):
        print(f"{tipo}: {market_share_final[i]*100:.2f}%")


matriz de transiçao inicial
[[0.8  0.1  0.05 0.03 0.02]
 [0.15 0.7  0.1  0.03 0.02]
 [0.15 0.1  0.6  0.1  0.05]
 [0.2  0.1  0.1  0.5  0.1 ]
 [0.2  0.15 0.15 0.1  0.4 ]]
numero de meses
24
matriz de transiçao apos os meses
[[0.44792712 0.25636232 0.16029582 0.08449816 0.05091658]
 [0.44790395 0.25636885 0.16030515 0.08450295 0.0509191 ]
 [0.44791126 0.25636484 0.16030284 0.08450228 0.05091878]
 [0.44791509 0.25636445 0.16030107 0.08450119 0.0509182 ]
 [0.44791286 0.25636521 0.16030193 0.08450159 0.0509184 ]]
Market Share inicial
Conservador: 20.00%
Moderado: 20.00%
Arrojado: 20.00%
Agressivo: 20.00%
Ultra-agressivo: 20.00%
Market Share após 24 meses:
Conservador: 44.79%
Moderado: 25.64%
Arrojado: 16.03%
Agressivo: 8.45%
Ultra-agressivo: 5.09%
